import { readFile, writeFile, mkdir } from "node:fs/promises";
import { createRequire } from "node:module";
import { resolve } from "node:path";
import { stdout } from "node:process";
import { countries } from "country-flag-icons";
import { JSDOM } from "jsdom";
import prettier from "prettier";

// Pinned development input; no flag package or remote image service at runtime.
const require = createRequire(import.meta.url);
const source = resolve(
  require.resolve("country-flag-icons/package.json"),
  "..",
);
const version = JSON.parse(
  await readFile(resolve(source, "package.json"), "utf8"),
).version;
if (version !== "1.6.20")
  throw new Error("Review artwork before changing its pinned version.");
const excluded = new Set(["IL", "AC", "TA", "EU", "IC", "XA", "XO", "XC"]);
const codes = countries
  .filter((code) => /^[A-Z]{2}$/.test(code) && !excluded.has(code))
  .sort();
// All 249 ISO 3166-1 entries except IL, plus XK (Kosovo).
if (codes.length !== 249)
  throw new Error(`Review catalog coverage: ${codes.length} entries.`);
const names = new Intl.DisplayNames(["en"], { type: "region" });
const nameOverrides = {
  PS: "Palestine",
  VA: "Vatican City",
  CD: "Democratic Republic of the Congo",
  CG: "Republic of the Congo",
};
const slug = (name) =>
  name
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/&/g, "and")
    .replace(/[’']/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
const entries = codes.map((code) => {
  const name = nameOverrides[code] ?? names.of(code);
  return { code, name, slug: slug(name) };
});
const format = async (text) => prettier.format(text, { parser: "typescript" });
await mkdir("src/flags/data", { recursive: true });
const dom = new JSDOM();
const parser = new dom.window.DOMParser();
for (const { code } of entries) {
  if (code === "PK" || code === "US") continue; // Original Zeenat artwork stays inline.
  const svg = (
    await readFile(resolve(source, "3x2", `${code}.svg`), "utf8")
  ).trim();
  const doc = parser.parseFromString(svg, "image/svg+xml");
  if (
    doc.querySelector(
      "parsererror, script, foreignObject, image, style, animate, animateTransform",
    )
  ) {
    throw new Error(`Unsafe or unsupported SVG: ${code}`);
  }
  for (const node of doc.querySelectorAll("*")) {
    for (const attr of node.attributes) {
      if (
        /^on/i.test(attr.name) ||
        (/href$/i.test(attr.name) && !attr.value.startsWith("#")) ||
        /url\(\s*["']?(?!#)/i.test(attr.value)
      ) {
        throw new Error(`External or active SVG content: ${code} ${attr.name}`);
      }
    }
  }
  const toNode = (element) => [
    element.localName,
    Object.fromEntries(
      [...element.attributes].map((attr) => [attr.name, attr.value]),
    ),
    [...element.children]
      .filter((child) => !["title", "desc"].includes(child.localName))
      .map(toNode),
  ];
  await writeFile(
    `src/flags/data/${code.toLowerCase()}.ts`,
    await format(
      `// Generated from country-flag-icons ${version} (MIT). See THIRD_PARTY_NOTICES.md.\nimport type { FlagNode } from "../render";\nconst artwork: FlagNode = ${JSON.stringify(toNode(doc.documentElement))};\nexport default artwork;\n`,
    ),
  );
}
dom.window.close();
await writeFile(
  "src/flags/catalog.ts",
  await format(
    `// Generated by npm run flags:generate. Do not edit by hand.\nexport const flagCatalog = ${JSON.stringify(entries)} as const;\nexport type CountryFlagCode = (typeof flagCatalog)[number]["code"];\nexport type CountryFlagName = (typeof flagCatalog)[number]["slug"];\n`,
  ),
);
await writeFile(
  "src/flags/loaders.ts",
  await format(
    `// Generated from country-flag-icons ${version} (MIT).\nexport const flagLoaders = {\n${entries
      .filter(({ code }) => code !== "PK" && code !== "US")
      .map(
        ({ code }) => `${code}: () => import("./data/${code.toLowerCase()}"),`,
      )
      .join("\n")}\n} as const;\n`,
  ),
);
const license = await readFile(resolve(source, "LICENSE"), "utf8");
await writeFile(
  "THIRD_PARTY_NOTICES.md",
  `# Zeenat.js third-party notices\n\n## country-flag-icons ${version}\n\nSource: https://github.com/catamphetamine/country-flag-icons\n\nThe generated SVG modules in src/flags/data derive from the pinned npm package's 3x2 artwork. They are simplified decorative icons, not official flag construction specifications. Pakistan and United States artwork remains original Zeenat.js geometry.\n\n${license}`,
);
await writeFile(
  "docs/flags-catalog.md",
  `# Zeenat.js flag catalog\n\nGenerated from the pinned artwork release with npm run flags:generate.\n\nCoverage: 248 ISO 3166-1 countries/territories (IL is excluded), plus Kosovo (XK): 249 selectable entries. This catalog is not a statement about recognition or visitors' identity.\n\nUse an English slug below or a case-insensitive two-letter code as the flag option.\n\n| Code | Flag name | Slug |\n| --- | --- | --- |\n${entries.map(({ code, name, slug }) => `| ${code} | ${name} | ${slug} |`).join("\n")}\n`,
);
stdout.write(
  `Generated ${entries.length} catalog entries and ${entries.length - 2} lazy SVG modules.\n`,
);
